### ISSUE TITLE
Suggest using the URLSearchParams built-in

### ISSUE THREAD

**Issue by tredondo** [unshiftio/querystringify#37]
The URL standard includes the [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) interface which in many cases should be able to replace this module. @sindresorhus is also [considering](https://github.com/sindresorhus/query-string/issues/307) suggesting it in his `query-string` module README.

This module has 10M weekly downloads. It would really help mentioning the built-in, to help avoid cargo cult usage of this module when not necessary.

The twice as popular [querystring](https://www.npmjs.com/package/querystring) package deprecated itself in favor of URLSearchParams.

**Comment by jimmywarting** [comment]
agree, this lib don't even support double entity like `foo=1&foo=2`
something that URLSearchParams can do for you...

this lib almost the the same thing as 
```js
Object.fromEntries(new URLSearchParams('?foo=bar')) 
`?${new URLSearchParams({foo: 'bar'})}`
```

**Comment by lpinca** [comment]
> this lib almost the the same thing as this, but with much more code...

This module was built years ago when `URLSearchParams` was not supported everywhere. This module works in IE6. Also this module is deadly simple by design.

Unlike alternatives like `qs` or `query-string` this module is around 400 bytes when minified and gzipped.

I agree that it would be better to use `URLSearchParams` when possible, but I do not think that using this small library is a problem. Developers should evaluate themselves.

**Comment by lpinca** [comment]
Feel free to open a PR with the suggestion.

**Comment by tredondo** [comment]
Great, see #38.
